name: CI, Pull request checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  frontend-CI:
    name: frontend pipeline
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Check prettier formatting
      run: |
        cd frontend
        npm run check

    - name: Build the project
      run: |
        cd frontend
        npm run build

  backend-CI:
    name: backend pipeline
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Check prettier formatting
        run: |
          cd backend
          npm run check

      - name: Build the project
        run: |
          cd backend
          npm run setup_prisma
          npm run build